/**
 * PLATFORMA KATALOGI — xizmatlar va davlatlar (yagona manba).
 *
 * Ikki joydan ishlatiladi:
 *  - prisma/seed.ts          — to'liq seed (dev/birinchi o'rnatish)
 *  - prisma/sync-catalog.ts  — prod'da FAQAT katalogni yangilash (xavfsiz)
 *
 * Davlatlar ro'yxati LZT Market qo'llaydigan barcha davlatlarni qamraydi
 * (GET /telegram/params -> country.values). LZT ISO2 bilan ishlaydi, shu bois
 * `iso2` to'g'ri bo'lsa yangi davlat avtomatik sotuvga yaroqli.
 */

// ── Xizmatlar (HeroSMS kodi; telegram = SPIDER real SIM) ──
export const SERVICES = [
  { slug: 'telegram', nameUz: 'Telegram', nameRu: 'Telegram', emoji: '💙', heroCode: 'tg', telegramOnly: true, position: 1 },
  // Spam-blokli Telegram akkauntlari — ANCHA ARZON. Mijoz kirisha oladi,
  // lekin notanishlarga birinchi bo'lib yoza olmaydi (kanal/guruh/bot OK).
  // Narxlashda ham, vitrinada ham toza (spamsiz) Telegram'dan alohida turadi.
  { slug: 'telegram_spam', nameUz: 'Telegram (spam)', nameRu: 'Telegram (спам)', emoji: '💤', heroCode: null, telegramOnly: true, position: 2 },
  { slug: 'whatsapp', nameUz: 'WhatsApp', nameRu: 'WhatsApp', emoji: '💚', heroCode: 'wa', telegramOnly: false, position: 3 },
  { slug: 'instagram', nameUz: 'Instagram', nameRu: 'Instagram', emoji: '📸', heroCode: 'ig', telegramOnly: false, position: 4 },
  { slug: 'google', nameUz: 'Google / Gmail', nameRu: 'Google / Gmail', emoji: '✉️', heroCode: 'go', telegramOnly: false, position: 5 },
  { slug: 'facebook', nameUz: 'Facebook', nameRu: 'Facebook', emoji: '📘', heroCode: 'fb', telegramOnly: false, position: 6 },
  { slug: 'tiktok', nameUz: 'TikTok', nameRu: 'TikTok', emoji: '🎶', heroCode: 'lf', telegramOnly: false, position: 7 },
  { slug: 'twitter', nameUz: 'Twitter / X', nameRu: 'Twitter / X', emoji: '✖️', heroCode: 'tw', telegramOnly: false, position: 8 },
  { slug: 'viber', nameUz: 'Viber', nameRu: 'Viber', emoji: '💜', heroCode: 'vi', telegramOnly: false, position: 9 },
  { slug: 'uber', nameUz: 'Uber', nameRu: 'Uber', emoji: '🚗', heroCode: 'ub', telegramOnly: false, position: 10 },
];

// ── Davlatlar (iso2 = SPIDER; heroCode = HeroSMS) ──
export const COUNTRIES = [
  { slug: 'uzbekistan', nameUz: 'O’zbekiston', nameRu: 'Узбекистан', flag: '🇺🇿', iso2: 'UZ', heroCode: '40' },
  { slug: 'usa', nameUz: 'AQSH', nameRu: 'США', flag: '🇺🇸', iso2: 'US', heroCode: '187' },
  { slug: 'kazakhstan', nameUz: 'Qozog’iston', nameRu: 'Казахстан', flag: '🇰🇿', iso2: 'KZ', heroCode: '2' },
  { slug: 'ukraine', nameUz: 'Ukraina', nameRu: 'Украина', flag: '🇺🇦', iso2: 'UA', heroCode: '1' },
  { slug: 'uk', nameUz: 'Angliya', nameRu: 'Англия', flag: '🇬🇧', iso2: 'GB', heroCode: '16' },
  { slug: 'india', nameUz: 'Hindiston', nameRu: 'Индия', flag: '🇮🇳', iso2: 'IN', heroCode: '22' },
  { slug: 'indonesia', nameUz: 'Indoneziya', nameRu: 'Индонезия', flag: '🇮🇩', iso2: 'ID', heroCode: '6' },
  { slug: 'philippines', nameUz: 'Filippin', nameRu: 'Филиппины', flag: '🇵🇭', iso2: 'PH', heroCode: '4' },
  { slug: 'vietnam', nameUz: 'Vetnam', nameRu: 'Вьетнам', flag: '🇻🇳', iso2: 'VN', heroCode: '10' },
  { slug: 'pakistan', nameUz: 'Pokiston', nameRu: 'Пакистан', flag: '🇵🇰', iso2: 'PK', heroCode: '66' },
  { slug: 'bangladesh', nameUz: 'Bangladesh', nameRu: 'Бангладеш', flag: '🇧🇩', iso2: 'BD', heroCode: '60' },
  { slug: 'thailand', nameUz: 'Tailand', nameRu: 'Таиланд', flag: '🇹🇭', iso2: 'TH', heroCode: '52' },
  { slug: 'malaysia', nameUz: 'Malayziya', nameRu: 'Малайзия', flag: '🇲🇾', iso2: 'MY', heroCode: '7' },
  { slug: 'myanmar', nameUz: 'Myanma', nameRu: 'Мьянма', flag: '🇲🇲', iso2: 'MM', heroCode: '5' },
  { slug: 'china', nameUz: 'Xitoy', nameRu: 'Китай', flag: '🇨🇳', iso2: 'CN', heroCode: '3' },
  { slug: 'turkey', nameUz: 'Turkiya', nameRu: 'Турция', flag: '🇹🇷', iso2: 'TR', heroCode: '62' },
  { slug: 'saudi', nameUz: 'Saudiya', nameRu: 'Саудовская Аравия', flag: '🇸🇦', iso2: 'SA', heroCode: '53' },
  { slug: 'oman', nameUz: 'Ummon', nameRu: 'Оман', flag: '🇴🇲', iso2: 'OM', heroCode: '107' },
  { slug: 'egypt', nameUz: 'Misr', nameRu: 'Египет', flag: '🇪🇬', iso2: 'EG', heroCode: '21' },
  { slug: 'morocco', nameUz: 'Marokko', nameRu: 'Марокко', flag: '🇲🇦', iso2: 'MA', heroCode: '37' },
  { slug: 'nigeria', nameUz: 'Nigeriya', nameRu: 'Нигерия', flag: '🇳🇬', iso2: 'NG', heroCode: '19' },
  { slug: 'kenya', nameUz: 'Keniya', nameRu: 'Кения', flag: '🇰🇪', iso2: 'KE', heroCode: '8' },
  { slug: 'ghana', nameUz: 'Gana', nameRu: 'Гана', flag: '🇬🇭', iso2: 'GH', heroCode: '38' },
  { slug: 'south_africa', nameUz: 'Janubiy Afrika', nameRu: 'ЮАР', flag: '🇿🇦', iso2: 'ZA', heroCode: '31' },
  { slug: 'brazil', nameUz: 'Braziliya', nameRu: 'Бразилия', flag: '🇧🇷', iso2: 'BR', heroCode: '73' },
  { slug: 'argentina', nameUz: 'Argentina', nameRu: 'Аргентина', flag: '🇦🇷', iso2: 'AR', heroCode: '39' },
  { slug: 'chile', nameUz: 'Chili', nameRu: 'Чили', flag: '🇨🇱', iso2: 'CL', heroCode: '151' },
  { slug: 'colombia', nameUz: 'Kolumbiya', nameRu: 'Колумбия', flag: '🇨🇴', iso2: 'CO', heroCode: '33' },
  { slug: 'mexico', nameUz: 'Meksika', nameRu: 'Мексика', flag: '🇲🇽', iso2: 'MX', heroCode: '54' },
  { slug: 'canada', nameUz: 'Kanada', nameRu: 'Канада', flag: '🇨🇦', iso2: 'CA', heroCode: '36' },
  { slug: 'germany', nameUz: 'Germaniya', nameRu: 'Германия', flag: '🇩🇪', iso2: 'DE', heroCode: '43' },
  { slug: 'france', nameUz: 'Fransiya', nameRu: 'Франция', flag: '🇫🇷', iso2: 'FR', heroCode: '78' },
  { slug: 'spain', nameUz: 'Ispaniya', nameRu: 'Испания', flag: '🇪🇸', iso2: 'ES', heroCode: '56' },
  { slug: 'italy', nameUz: 'Italiya', nameRu: 'Италия', flag: '🇮🇹', iso2: 'IT', heroCode: '86' },
  { slug: 'netherlands', nameUz: 'Niderlandiya', nameRu: 'Нидерланды', flag: '🇳🇱', iso2: 'NL', heroCode: '48' },
  { slug: 'poland', nameUz: 'Polsha', nameRu: 'Польша', flag: '🇵🇱', iso2: 'PL', heroCode: '15' },
  { slug: 'romania', nameUz: 'Ruminiya', nameRu: 'Румыния', flag: '🇷🇴', iso2: 'RO', heroCode: '32' },
  // ── LZT Market qo'llaydigan QOLGAN davlatlar (Telegram akkauntlari) ──
  // Ro'yxat LZT API'ning o'zidan (`GET /telegram/params` -> country.values, 2026-10-01).
  // Tartib — LZT zaxira hajmi bo'yicha (ko'p akkauntlilar birinchi).
  // heroCode: null — bu davlatlar faqat Telegram (LZT) uchun; HeroSMS
  // xizmatlari vitrinada ularni avtomatik ko'rsatmaydi (heroCode filtri).
  { slug: 'ethiopia', nameUz: 'Efiopiya', nameRu: 'Эфиопия', flag: '🇪🇹', iso2: 'ET', heroCode: null },
  { slug: 'kyrgyzstan', nameUz: 'Qirg’iziston', nameRu: 'Киргизия', flag: '🇰🇬', iso2: 'KG', heroCode: null },
  { slug: 'iran', nameUz: 'Eron', nameRu: 'Иран', flag: '🇮🇷', iso2: 'IR', heroCode: null },
  { slug: 'yemen', nameUz: 'Yaman', nameRu: 'Йемен', flag: '🇾🇪', iso2: 'YE', heroCode: null },
  { slug: 'algeria', nameUz: 'Jazoir', nameRu: 'Алжир', flag: '🇩🇿', iso2: 'DZ', heroCode: null },
  { slug: 'iraq', nameUz: 'Iroq', nameRu: 'Ирак', flag: '🇮🇶', iso2: 'IQ', heroCode: null },
  { slug: 'armenia', nameUz: 'Armaniston', nameRu: 'Армения', flag: '🇦🇲', iso2: 'AM', heroCode: null },
  { slug: 'portugal', nameUz: 'Portugaliya', nameRu: 'Португалия', flag: '🇵🇹', iso2: 'PT', heroCode: null },
  { slug: 'peru', nameUz: 'Peru', nameRu: 'Перу', flag: '🇵🇪', iso2: 'PE', heroCode: null },
  { slug: 'sri_lanka', nameUz: 'Shri-Lanka', nameRu: 'Шри-Ланка', flag: '🇱🇰', iso2: 'LK', heroCode: null },
  { slug: 'cambodia', nameUz: 'Kambodja', nameRu: 'Камбоджа', flag: '🇰🇭', iso2: 'KH', heroCode: null },
  { slug: 'japan', nameUz: 'Yaponiya', nameRu: 'Япония', flag: '🇯🇵', iso2: 'JP', heroCode: null },
  { slug: 'afghanistan', nameUz: 'Afg’oniston', nameRu: 'Афганистан', flag: '🇦🇫', iso2: 'AF', heroCode: null },
  { slug: 'somalia', nameUz: 'Somali', nameRu: 'Сомали', flag: '🇸🇴', iso2: 'SO', heroCode: null },
  { slug: 'czechia', nameUz: 'Chexiya', nameRu: 'Чехия', flag: '🇨🇿', iso2: 'CZ', heroCode: null },
  { slug: 'israel', nameUz: 'Isroil', nameRu: 'Израиль', flag: '🇮🇱', iso2: 'IL', heroCode: null },
  { slug: 'tajikistan', nameUz: 'Tojikiston', nameRu: 'Таджикистан', flag: '🇹🇯', iso2: 'TJ', heroCode: null },
  { slug: 'syria', nameUz: 'Suriya', nameRu: 'Сирия', flag: '🇸🇾', iso2: 'SY', heroCode: null },
  { slug: 'tunisia', nameUz: 'Tunis', nameRu: 'Тунис', flag: '🇹🇳', iso2: 'TN', heroCode: null },
  { slug: 'tanzania', nameUz: 'Tanzaniya', nameRu: 'Танзания', flag: '🇹🇿', iso2: 'TZ', heroCode: null },
  { slug: 'venezuela', nameUz: 'Venesuela', nameRu: 'Венесуэла', flag: '🇻🇪', iso2: 'VE', heroCode: null },
  { slug: 'nepal', nameUz: 'Nepal', nameRu: 'Непал', flag: '🇳🇵', iso2: 'NP', heroCode: null },
  { slug: 'estonia', nameUz: 'Estoniya', nameRu: 'Эстония', flag: '🇪🇪', iso2: 'EE', heroCode: null },
  { slug: 'hungary', nameUz: 'Vengriya', nameRu: 'Венгрия', flag: '🇭🇺', iso2: 'HU', heroCode: null },
  { slug: 'ecuador', nameUz: 'Ekvador', nameRu: 'Эквадор', flag: '🇪🇨', iso2: 'EC', heroCode: null },
  { slug: 'ivory_coast', nameUz: 'Kot-d’Ivuar', nameRu: 'Кот-д’Ивуар', flag: '🇨🇮', iso2: 'CI', heroCode: null },
  { slug: 'dominican_republic', nameUz: 'Dominikana', nameRu: 'Доминикана', flag: '🇩🇴', iso2: 'DO', heroCode: null },
  { slug: 'uae', nameUz: 'BAA (Dubay)', nameRu: 'ОАЭ', flag: '🇦🇪', iso2: 'AE', heroCode: null },
  { slug: 'greece', nameUz: 'Gretsiya', nameRu: 'Греция', flag: '🇬🇷', iso2: 'GR', heroCode: null },
  { slug: 'guatemala', nameUz: 'Gvatemala', nameRu: 'Гватемала', flag: '🇬🇹', iso2: 'GT', heroCode: null },
  { slug: 'madagascar', nameUz: 'Madagaskar', nameRu: 'Мадагаскар', flag: '🇲🇬', iso2: 'MG', heroCode: null },
  { slug: 'cameroon', nameUz: 'Kamerun', nameRu: 'Камерун', flag: '🇨🇲', iso2: 'CM', heroCode: null },
  { slug: 'uganda', nameUz: 'Uganda', nameRu: 'Уганда', flag: '🇺🇬', iso2: 'UG', heroCode: null },
  { slug: 'zimbabwe', nameUz: 'Zimbabve', nameRu: 'Зимбабве', flag: '🇿🇼', iso2: 'ZW', heroCode: null },
  { slug: 'australia', nameUz: 'Avstraliya', nameRu: 'Австралия', flag: '🇦🇺', iso2: 'AU', heroCode: null },
  { slug: 'turkmenistan', nameUz: 'Turkmaniston', nameRu: 'Туркменистан', flag: '🇹🇲', iso2: 'TM', heroCode: null },
  { slug: 'belarus', nameUz: 'Belarus', nameRu: 'Беларусь', flag: '🇧🇾', iso2: 'BY', heroCode: null },
  { slug: 'lebanon', nameUz: 'Livan', nameRu: 'Ливан', flag: '🇱🇧', iso2: 'LB', heroCode: null },
  { slug: 'new_zealand', nameUz: 'Yangi Zelandiya', nameRu: 'Новая Зеландия', flag: '🇳🇿', iso2: 'NZ', heroCode: null },
  { slug: 'cuba', nameUz: 'Kuba', nameRu: 'Куба', flag: '🇨🇺', iso2: 'CU', heroCode: null },
  { slug: 'lithuania', nameUz: 'Litva', nameRu: 'Литва', flag: '🇱🇹', iso2: 'LT', heroCode: null },
  { slug: 'moldova', nameUz: 'Moldova', nameRu: 'Молдова', flag: '🇲🇩', iso2: 'MD', heroCode: null },
  { slug: 'ireland', nameUz: 'Irlandiya', nameRu: 'Ирландия', flag: '🇮🇪', iso2: 'IE', heroCode: null },
  { slug: 'senegal', nameUz: 'Senegal', nameRu: 'Сенегал', flag: '🇸🇳', iso2: 'SN', heroCode: null },
  { slug: 'rwanda', nameUz: 'Ruanda', nameRu: 'Руанда', flag: '🇷🇼', iso2: 'RW', heroCode: null },
  { slug: 'sweden', nameUz: 'Shvetsiya', nameRu: 'Швеция', flag: '🇸🇪', iso2: 'SE', heroCode: null },
  { slug: 'latvia', nameUz: 'Latviya', nameRu: 'Латвия', flag: '🇱🇻', iso2: 'LV', heroCode: null },
  { slug: 'bulgaria', nameUz: 'Bolgariya', nameRu: 'Болгария', flag: '🇧🇬', iso2: 'BG', heroCode: null },
  { slug: 'belgium', nameUz: 'Belgiya', nameRu: 'Бельгия', flag: '🇧🇪', iso2: 'BE', heroCode: null },
  { slug: 'georgia', nameUz: 'Gruziya', nameRu: 'Грузия', flag: '🇬🇪', iso2: 'GE', heroCode: null },
  { slug: 'azerbaijan', nameUz: 'Ozarbayjon', nameRu: 'Азербайджан', flag: '🇦🇿', iso2: 'AZ', heroCode: null },
  { slug: 'libya', nameUz: 'Liviya', nameRu: 'Ливия', flag: '🇱🇾', iso2: 'LY', heroCode: null },
  { slug: 'niger', nameUz: 'Niger', nameRu: 'Нигер', flag: '🇳🇪', iso2: 'NE', heroCode: null },
  { slug: 'austria', nameUz: 'Avstriya', nameRu: 'Австрия', flag: '🇦🇹', iso2: 'AT', heroCode: null },
  { slug: 'burkina_faso', nameUz: 'Burkina-Faso', nameRu: 'Буркина-Фасо', flag: '🇧🇫', iso2: 'BF', heroCode: null },
  { slug: 'albania', nameUz: 'Albaniya', nameRu: 'Албания', flag: '🇦🇱', iso2: 'AL', heroCode: null },
  { slug: 'paraguay', nameUz: 'Paragvay', nameRu: 'Парагвай', flag: '🇵🇾', iso2: 'PY', heroCode: null },
  { slug: 'slovakia', nameUz: 'Slovakiya', nameRu: 'Словакия', flag: '🇸🇰', iso2: 'SK', heroCode: null },
  { slug: 'hong_kong', nameUz: 'Gonkong', nameRu: 'Гонконг', flag: '🇭🇰', iso2: 'HK', heroCode: null },
  { slug: 'honduras', nameUz: 'Gonduras', nameRu: 'Гондурас', flag: '🇭🇳', iso2: 'HN', heroCode: null },
  { slug: 'angola', nameUz: 'Angola', nameRu: 'Ангола', flag: '🇦🇴', iso2: 'AO', heroCode: null },
  { slug: 'jordan', nameUz: 'Iordaniya', nameRu: 'Иордания', flag: '🇯🇴', iso2: 'JO', heroCode: null },
  { slug: 'panama', nameUz: 'Panama', nameRu: 'Панама', flag: '🇵🇦', iso2: 'PA', heroCode: null },
  { slug: 'costa_rica', nameUz: 'Kosta-Rika', nameRu: 'Коста-Рика', flag: '🇨🇷', iso2: 'CR', heroCode: null },
  { slug: 'slovenia', nameUz: 'Sloveniya', nameRu: 'Словения', flag: '🇸🇮', iso2: 'SI', heroCode: null },
  { slug: 'congo_dr', nameUz: 'Kongo (KDR)', nameRu: 'ДР Конго', flag: '🇨🇩', iso2: 'CD', heroCode: null },
  { slug: 'nicaragua', nameUz: 'Nikaragua', nameRu: 'Никарагуа', flag: '🇳🇮', iso2: 'NI', heroCode: null },
  { slug: 'serbia', nameUz: 'Serbiya', nameRu: 'Сербия', flag: '🇷🇸', iso2: 'RS', heroCode: null },
  { slug: 'croatia', nameUz: 'Xorvatiya', nameRu: 'Хорватия', flag: '🇭🇷', iso2: 'HR', heroCode: null },
  { slug: 'haiti', nameUz: 'Gaiti', nameRu: 'Гаити', flag: '🇭🇹', iso2: 'HT', heroCode: null },
  { slug: 'bolivia', nameUz: 'Boliviya', nameRu: 'Боливия', flag: '🇧🇴', iso2: 'BO', heroCode: null },
  { slug: 'el_salvador', nameUz: 'Salvador', nameRu: 'Сальвадор', flag: '🇸🇻', iso2: 'SV', heroCode: null },
  { slug: 'finland', nameUz: 'Finlyandiya', nameRu: 'Финляндия', flag: '🇫🇮', iso2: 'FI', heroCode: null },
  { slug: 'papua_new_guinea', nameUz: 'Papua-Yangi Gvineya', nameRu: 'Папуа-Новая Гвинея', flag: '🇵🇬', iso2: 'PG', heroCode: null },
  { slug: 'sudan', nameUz: 'Sudan', nameRu: 'Судан', flag: '🇸🇩', iso2: 'SD', heroCode: null },
  { slug: 'togo', nameUz: 'Togo', nameRu: 'Того', flag: '🇹🇬', iso2: 'TG', heroCode: null },
  { slug: 'jamaica', nameUz: 'Yamayka', nameRu: 'Ямайка', flag: '🇯🇲', iso2: 'JM', heroCode: null },
  { slug: 'guyana', nameUz: 'Gayana', nameRu: 'Гайана', flag: '🇬🇾', iso2: 'GY', heroCode: null },
  { slug: 'zambia', nameUz: 'Zambiya', nameRu: 'Замбия', flag: '🇿🇲', iso2: 'ZM', heroCode: null },
  { slug: 'denmark', nameUz: 'Daniya', nameRu: 'Дания', flag: '🇩🇰', iso2: 'DK', heroCode: null },
  { slug: 'north_macedonia', nameUz: 'Shimoliy Makedoniya', nameRu: 'Северная Македония', flag: '🇲🇰', iso2: 'MK', heroCode: null },
  { slug: 'bosnia', nameUz: 'Bosniya va Gertsegovina', nameRu: 'Босния и Герцеговина', flag: '🇧🇦', iso2: 'BA', heroCode: null },
  { slug: 'mozambique', nameUz: 'Mozambik', nameRu: 'Мозамбик', flag: '🇲🇿', iso2: 'MZ', heroCode: null },
  { slug: 'benin', nameUz: 'Benin', nameRu: 'Бенин', flag: '🇧🇯', iso2: 'BJ', heroCode: null },
  { slug: 'mauritius', nameUz: 'Mavrikiy', nameRu: 'Маврикий', flag: '🇲🇺', iso2: 'MU', heroCode: null },
  { slug: 'taiwan', nameUz: 'Tayvan', nameRu: 'Тайвань', flag: '🇹🇼', iso2: 'TW', heroCode: null },
  { slug: 'mali', nameUz: 'Mali', nameRu: 'Мали', flag: '🇲🇱', iso2: 'ML', heroCode: null },
  { slug: 'uruguay', nameUz: 'Urugvay', nameRu: 'Уругвай', flag: '🇺🇾', iso2: 'UY', heroCode: null },
  { slug: 'south_korea', nameUz: 'Janubiy Koreya', nameRu: 'Южная Корея', flag: '🇰🇷', iso2: 'KR', heroCode: null },
  { slug: 'switzerland', nameUz: 'Shveytsariya', nameRu: 'Швейцария', flag: '🇨🇭', iso2: 'CH', heroCode: null },
  { slug: 'mauritania', nameUz: 'Mavritaniya', nameRu: 'Мавритания', flag: '🇲🇷', iso2: 'MR', heroCode: null },
  { slug: 'namibia', nameUz: 'Namibiya', nameRu: 'Намибия', flag: '🇳🇦', iso2: 'NA', heroCode: null },
  { slug: 'reunion', nameUz: 'Reyunon', nameRu: 'Реюньон', flag: '🇷🇪', iso2: 'RE', heroCode: null },
  { slug: 'botswana', nameUz: 'Botsvana', nameRu: 'Ботсвана', flag: '🇧🇼', iso2: 'BW', heroCode: null },
  { slug: 'kuwait', nameUz: 'Quvayt', nameRu: 'Кувейт', flag: '🇰🇼', iso2: 'KW', heroCode: null },
  { slug: 'malawi', nameUz: 'Malavi', nameRu: 'Малави', flag: '🇲🇼', iso2: 'MW', heroCode: null },
  { slug: 'norway', nameUz: 'Norvegiya', nameRu: 'Норвегия', flag: '🇳🇴', iso2: 'NO', heroCode: null },
  { slug: 'bhutan', nameUz: 'Butan', nameRu: 'Бутан', flag: '🇧🇹', iso2: 'BT', heroCode: null },
  { slug: 'maldives', nameUz: 'Maldiv orollari', nameRu: 'Мальдивы', flag: '🇲🇻', iso2: 'MV', heroCode: null },
  { slug: 'mongolia', nameUz: 'Mongoliya', nameRu: 'Монголия', flag: '🇲🇳', iso2: 'MN', heroCode: null },
  { slug: 'palestine', nameUz: 'Falastin', nameRu: 'Палестина', flag: '🇵🇸', iso2: 'PS', heroCode: null },
  { slug: 'puerto_rico', nameUz: 'Puerto-Riko', nameRu: 'Пуэрто-Рико', flag: '🇵🇷', iso2: 'PR', heroCode: null },
  { slug: 'burundi', nameUz: 'Burundi', nameRu: 'Бурунди', flag: '🇧🇮', iso2: 'BI', heroCode: null },
  { slug: 'singapore', nameUz: 'Singapur', nameRu: 'Сингапур', flag: '🇸🇬', iso2: 'SG', heroCode: null },
  { slug: 'qatar', nameUz: 'Qatar', nameRu: 'Катар', flag: '🇶🇦', iso2: 'QA', heroCode: null },
  { slug: 'eswatini', nameUz: 'Esvatini', nameRu: 'Эсватини', flag: '🇸🇿', iso2: 'SZ', heroCode: null },
  { slug: 'chad', nameUz: 'Chad', nameRu: 'Чад', flag: '🇹🇩', iso2: 'TD', heroCode: null },
  { slug: 'luxembourg', nameUz: 'Lyuksemburg', nameRu: 'Люксембург', flag: '🇱🇺', iso2: 'LU', heroCode: null },
  { slug: 'curacao', nameUz: 'Kyurasao', nameRu: 'Кюрасао', flag: '🇨🇼', iso2: 'CW', heroCode: null },
  { slug: 'congo', nameUz: 'Kongo', nameRu: 'Конго', flag: '🇨🇬', iso2: 'CG', heroCode: null },
  { slug: 'kosovo', nameUz: 'Kosovo', nameRu: 'Косово', flag: '🇽🇰', iso2: 'XK', heroCode: null },
  { slug: 'cyprus', nameUz: 'Kipr', nameRu: 'Кипр', flag: '🇨🇾', iso2: 'CY', heroCode: null },
  { slug: 'brunei', nameUz: 'Bruney', nameRu: 'Бруней', flag: '🇧🇳', iso2: 'BN', heroCode: null },
  { slug: 'suriname', nameUz: 'Surinam', nameRu: 'Суринам', flag: '🇸🇷', iso2: 'SR', heroCode: null },
  { slug: 'djibouti', nameUz: 'Jibuti', nameRu: 'Джибути', flag: '🇩🇯', iso2: 'DJ', heroCode: null },
  { slug: 'greenland', nameUz: 'Grenlandiya', nameRu: 'Гренландия', flag: '🇬🇱', iso2: 'GL', heroCode: null },
  { slug: 'iceland', nameUz: 'Islandiya', nameRu: 'Исландия', flag: '🇮🇸', iso2: 'IS', heroCode: null },
  { slug: 'trinidad', nameUz: 'Trinidad va Tobago', nameRu: 'Тринидад и Тобаго', flag: '🇹🇹', iso2: 'TT', heroCode: null },
  { slug: 'guadeloupe', nameUz: 'Gvadelupa', nameRu: 'Гваделупа', flag: '🇬🇵', iso2: 'GP', heroCode: null },
  { slug: 'french_polynesia', nameUz: 'Fransuz Polineziyasi', nameRu: 'Французская Полинезия', flag: '🇵🇫', iso2: 'PF', heroCode: null },
  { slug: 'south_sudan', nameUz: 'Janubiy Sudan', nameRu: 'Южный Судан', flag: '🇸🇸', iso2: 'SS', heroCode: null },
  { slug: 'bahrain', nameUz: 'Bahrayn', nameRu: 'Бахрейн', flag: '🇧🇭', iso2: 'BH', heroCode: null },
  { slug: 'guam', nameUz: 'Guam', nameRu: 'Гуам', flag: '🇬🇺', iso2: 'GU', heroCode: null },
  { slug: 'malta', nameUz: 'Malta', nameRu: 'Мальта', flag: '🇲🇹', iso2: 'MT', heroCode: null },
  { slug: 'guinea', nameUz: 'Gvineya', nameRu: 'Гвинея', flag: '🇬🇳', iso2: 'GN', heroCode: null },
  { slug: 'gambia', nameUz: 'Gambiya', nameRu: 'Гамбия', flag: '🇬🇲', iso2: 'GM', heroCode: null },
  { slug: 'gabon', nameUz: 'Gabon', nameRu: 'Габон', flag: '🇬🇦', iso2: 'GA', heroCode: null },
  { slug: 'montenegro', nameUz: 'Chernogoriya', nameRu: 'Черногория', flag: '🇲🇪', iso2: 'ME', heroCode: null },
  { slug: 'sierra_leone', nameUz: 'Syerra-Leone', nameRu: 'Сьерра-Леоне', flag: '🇸🇱', iso2: 'SL', heroCode: null },
  { slug: 'lesotho', nameUz: 'Lesoto', nameRu: 'Лесото', flag: '🇱🇸', iso2: 'LS', heroCode: null },
  { slug: 'seychelles', nameUz: 'Seyshel orollari', nameRu: 'Сейшелы', flag: '🇸🇨', iso2: 'SC', heroCode: null },
  { slug: 'new_caledonia', nameUz: 'Yangi Kaledoniya', nameRu: 'Новая Каледония', flag: '🇳🇨', iso2: 'NC', heroCode: null },
  { slug: 'martinique', nameUz: 'Martinika', nameRu: 'Мартиника', flag: '🇲🇶', iso2: 'MQ', heroCode: null },
  { slug: 'laos', nameUz: 'Laos', nameRu: 'Лаос', flag: '🇱🇦', iso2: 'LA', heroCode: null },
  { slug: 'french_guiana', nameUz: 'Fransuz Gvianasi', nameRu: 'Французская Гвиана', flag: '🇬🇫', iso2: 'GF', heroCode: null },
  { slug: 'liberia', nameUz: 'Liberiya', nameRu: 'Либерия', flag: '🇱🇷', iso2: 'LR', heroCode: null },
  { slug: 'equatorial_guinea', nameUz: 'Ekvatorial Gvineya', nameRu: 'Экваториальная Гвинея', flag: '🇬🇶', iso2: 'GQ', heroCode: null },
  { slug: 'fiji', nameUz: 'Fiji', nameRu: 'Фиджи', flag: '🇫🇯', iso2: 'FJ', heroCode: null },
  { slug: 'belize', nameUz: 'Beliz', nameRu: 'Белиз', flag: '🇧🇿', iso2: 'BZ', heroCode: null },
  { slug: 'cape_verde', nameUz: 'Kabo-Verde', nameRu: 'Кабо-Верде', flag: '🇨🇻', iso2: 'CV', heroCode: null },
  { slug: 'bahamas', nameUz: 'Bagama orollari', nameRu: 'Багамы', flag: '🇧🇸', iso2: 'BS', heroCode: null },
  { slug: 'tonga', nameUz: 'Tonga', nameRu: 'Тонга', flag: '🇹🇴', iso2: 'TO', heroCode: null },
  { slug: 'grenada', nameUz: 'Grenada', nameRu: 'Гренада', flag: '🇬🇩', iso2: 'GD', heroCode: null },
  { slug: 'samoa', nameUz: 'Samoa', nameRu: 'Самоа', flag: '🇼🇸', iso2: 'WS', heroCode: null },
  { slug: 'saint_lucia', nameUz: 'Sent-Lyusiya', nameRu: 'Сент-Люсия', flag: '🇱🇨', iso2: 'LC', heroCode: null },
  { slug: 'barbados', nameUz: 'Barbados', nameRu: 'Барбадос', flag: '🇧🇧', iso2: 'BB', heroCode: null },
  { slug: 'solomon_islands', nameUz: 'Solomon orollari', nameRu: 'Соломоновы Острова', flag: '🇸🇧', iso2: 'SB', heroCode: null },
  { slug: 'mayotte', nameUz: 'Mayotta', nameRu: 'Майотта', flag: '🇾🇹', iso2: 'YT', heroCode: null },
  { slug: 'vanuatu', nameUz: 'Vanuatu', nameRu: 'Вануату', flag: '🇻🇺', iso2: 'VU', heroCode: null },
  { slug: 'dominica', nameUz: 'Dominika', nameRu: 'Доминика', flag: '🇩🇲', iso2: 'DM', heroCode: null },
  { slug: 'aruba', nameUz: 'Aruba', nameRu: 'Аруба', flag: '🇦🇼', iso2: 'AW', heroCode: null },
  { slug: 'monaco', nameUz: 'Monako', nameRu: 'Монако', flag: '🇲🇨', iso2: 'MC', heroCode: null },
  { slug: 'sao_tome', nameUz: 'San-Tome va Prinsipi', nameRu: 'Сан-Томе и Принсипи', flag: '🇸🇹', iso2: 'ST', heroCode: null },
  { slug: 'gibraltar', nameUz: 'Gibraltar', nameRu: 'Гибралтар', flag: '🇬🇮', iso2: 'GI', heroCode: null },
  { slug: 'andorra', nameUz: 'Andorra', nameRu: 'Андорра', flag: '🇦🇩', iso2: 'AD', heroCode: null },
  { slug: 'turks_caicos', nameUz: 'Terks va Kaykos', nameRu: 'Теркс и Кайкос', flag: '🇹🇨', iso2: 'TC', heroCode: null },
  { slug: 'guernsey', nameUz: 'Gernsi', nameRu: 'Гернси', flag: '🇬🇬', iso2: 'GG', heroCode: null },
  { slug: 'macau', nameUz: 'Makao', nameRu: 'Макао', flag: '🇲🇴', iso2: 'MO', heroCode: null },
  { slug: 'bermuda', nameUz: 'Bermuda', nameRu: 'Бермуды', flag: '🇧🇲', iso2: 'BM', heroCode: null },
  { slug: 'timor_leste', nameUz: 'Sharqiy Timor', nameRu: 'Восточный Тимор', flag: '🇹🇱', iso2: 'TL', heroCode: null },
  { slug: 'central_african_rep', nameUz: 'Markaziy Afrika Resp.', nameRu: 'ЦАР', flag: '🇨🇫', iso2: 'CF', heroCode: null },
  { slug: 'comoros', nameUz: 'Komor orollari', nameRu: 'Коморы', flag: '🇰🇲', iso2: 'KM', heroCode: null },
  { slug: 'saint_vincent', nameUz: 'Sent-Vinsent', nameRu: 'Сент-Винсент', flag: '🇻🇨', iso2: 'VC', heroCode: null },
  { slug: 'antigua', nameUz: 'Antigua va Barbuda', nameRu: 'Антигуа и Барбуда', flag: '🇦🇬', iso2: 'AG', heroCode: null },
  { slug: 'guinea_bissau', nameUz: 'Gvineya-Bisau', nameRu: 'Гвинея-Бисау', flag: '🇬🇼', iso2: 'GW', heroCode: null },
  { slug: 'cayman_islands', nameUz: 'Kayman orollari', nameRu: 'Каймановы острова', flag: '🇰🇾', iso2: 'KY', heroCode: null },
  { slug: 'american_samoa', nameUz: 'Amerika Samoasi', nameRu: 'Американское Самоа', flag: '🇦🇸', iso2: 'AS', heroCode: null },
  { slug: 'anguilla', nameUz: 'Angilya', nameRu: 'Ангилья', flag: '🇦🇮', iso2: 'AI', heroCode: null },
  { slug: 'northern_mariana', nameUz: 'Shimoliy Mariana', nameRu: 'Северные Марианские о-ва', flag: '🇲🇵', iso2: 'MP', heroCode: null },
  { slug: 'saint_pierre', nameUz: 'Sen-Pyer va Mikelon', nameRu: 'Сен-Пьер и Микелон', flag: '🇵🇲', iso2: 'PM', heroCode: null },
  { slug: 'us_virgin_islands', nameUz: 'Virjiniya orollari (AQSH)', nameRu: 'Виргинские о-ва (США)', flag: '🇻🇮', iso2: 'VI', heroCode: null },
  { slug: 'sint_maarten', nameUz: 'Sint-Marten', nameRu: 'Синт-Мартен', flag: '🇸🇽', iso2: 'SX', heroCode: null },
  { slug: 'kiribati', nameUz: 'Kiribati', nameRu: 'Кирибати', flag: '🇰🇮', iso2: 'KI', heroCode: null },
];
